// Korean - uses English as base structure
import en from "./en";
const ko: typeof en = JSON.parse(JSON.stringify(en));
Object.assign(ko.common, { signIn: "로그인", signUp: "회원가입", signOut: "로그아웃", getStarted: "시작하기", search: "검색", save: "저장", cancel: "취소", delete: "삭제", edit: "수정", back: "뒤로", next: "다음", submit: "제출", confirm: "확인", send: "보내기", apply: "지원", close: "닫기", yes: "예", no: "아니오", ok: "확인", loading: "로딩 중...", saving: "저장 중...", viewAll: "모두 보기", clearAll: "모두 지우기", clearFilters: "필터 초기화", noResults: "결과를 찾을 수 없습니다", email: "이메일", password: "비밀번호", fullName: "이름", phone: "전화번호", address: "주소", perHour: "/시간", hours: "시간", minutes: "분", yearsExp: "년 경력", bookNow: "지금 예약", refresh: "새로고침", accept: "수락", decline: "거절", remove: "제거", add: "추가", create: "만들기", update: "업데이트", upload: "업로드", download: "다운로드", pending: "대기 중", confirmed: "확인됨", completed: "완료됨", cancelled: "취소됨", inProgress: "진행 중", caregiver: "간병인", date: "날짜", time: "시간", duration: "기간", notes: "메모", description: "설명", location: "위치", settings: "설정", notifications: "알림", privacy: "개인정보", reviews: "리뷰", rating: "평점", message: "메시지", verified: "인증됨", weak: "약함", fair: "보통", good: "좋음", strong: "강함", copyright: "© 2026 {{brand}}. All rights reserved.", errorOccurred: "오류가 발생했습니다", tryAgain: "다시 시도해 주세요", minCharsToSearch: "검색하려면 2자 이상 입력하세요" });
Object.assign(ko.nav, { dashboard: "대시보드", messages: "메시지", favorites: "즐겨찾기", gpsTracking: "GPS 추적", myBookings: "내 예약", careGroups: "돌봄 그룹", careTeams: "돌봄 팀", findCare: "돌봄 찾기", findHelp: "도움 찾기", caredOnes: "돌봄 대상자", myLovedOnes: "내 사랑하는 사람", howItWorks: "이용 방법", trustSafety: "신뢰와 안전", myProfile: "내 프로필", notifications: "알림", becomeCaregiver: "간병인 되기", jobsBoard: "구인 게시판", providerDashboard: "제공자 대시보드", toggleTheme: "테마 전환" });
ko.site.challenged = { ...ko.site.challenged, name: "ChallengeD", heroTitle: "치매 돌봄,", heroHighlight: "함께", heroSubtitle: "가족과 함께 치매 돌봄을 조율하고, 전문 간병인을 찾고, 사랑하는 사람을 안전하게 지키세요.", ctaTitle: "치매 돌봄 여정은 여기서 시작됩니다", ctaButton: "치매 간병인 찾기", searchPlaceholder: "어떤 치매 돌봄이 필요하신가요?", howItWorksTitle: "ChallengeD 이용 방법", authSubtitle: "치매 돌봄, 함께", dashboardSubtitle: "치매 돌봄 개요", caredOneSingular: "사랑하는 사람", careGroupSingular: "돌봄 팀" };
ko.site.careconnected = { ...ko.site.careconnected, heroTitle: "신뢰할 수 있는 돌봄을 찾고,", heroHighlight: "연결되세요", heroSubtitle: "간병인 검색, 예약, 돌봄 팀과 조율, 실시간 추적을 한 곳에서.", ctaTitle: "완벽한 간병인을 찾을 준비가 되셨나요?", ctaButton: "간병인 찾기", searchPlaceholder: "어떤 유형의 돌봄이 필요하신가요?", howItWorksTitle: "CareCNC 이용 방법", authSubtitle: "신뢰할 수 있는 돌봄 찾기 및 관리", dashboardSubtitle: "돌봄 개요", caredOneSingular: "돌봄 대상자", careGroupSingular: "돌봄 그룹" };
Object.assign(ko.auth, { signingIn: "로그인 중...", creatingAccount: "계정 생성 중...", welcomeBack: "다시 오신 것을 환영합니다!", loginFailed: "로그인 실패", signupFailed: "가입 실패", fillAllFields: "모든 필드를 입력해 주세요", accountCreated: "계정이 생성되었습니다! 이메일을 확인해 주세요.", forgotPassword: "비밀번호를 잊으셨나요?", resetPassword: "비밀번호 재설정", sendResetLink: "재설정 링크 보내기", resetLinkSent: "재설정 링크가 전송되었습니다!" });
Object.assign(ko.dashboard, { welcomeBack: "다시 오신 것을 환영합니다, {{name}}님!", upcomingBookings: "예정된 예약", pendingTasks: "대기 중인 작업", unreadMessages: "읽지 않은 메시지", careTasks: "돌봄 작업", quickActions: "빠른 작업", customizeDashboard: "대시보드 맞춤설정" });
Object.assign(ko.search, { searchCaregivers: "간병인 검색...", highestRated: "최고 평점", filters: "필터", hourlyRate: "시급", verifiedOnly: "인증만", caregiversFound: "{{count}}명의 간병인을 찾았습니다", noMatch: "조건에 맞는 간병인이 없습니다." });
Object.assign(ko.bookings, { myBookings: "내 예약", bookNew: "새 예약", upcoming: "예정", past: "과거", cancelBooking: "예약 취소", reschedule: "일정 변경", leaveReview: "리뷰 작성", noUpcoming: "예정된 예약이 없습니다" });
Object.assign(ko.messages, { messages: "메시지", newMessage: "새 메시지", typeMessage: "메시지를 입력하세요...", noConversations: "대화가 아직 없습니다", noMessages: "메시지가 아직 없습니다." });
ko.notFound = { title: "404", subtitle: "페이지를 찾을 수 없습니다", returnHome: "홈으로 돌아가기" };
ko.language = { label: "언어", en: "English", "zh-CN": "简体中文", "zh-TW": "繁體中文", ja: "日本語", ko: "한국어", es: "Español", fr: "Français", de: "Deutsch", pt: "Português", hi: "हिन्दी", ar: "العربية", vi: "Tiếng Việt", th: "ไทย", id: "Bahasa Indonesia", tl: "Filipino", ru: "Русский", it: "Italiano" };
export default ko;
